'use client';

import CodeBlock from '@/components/CodeBlock';
import { useTranslations } from '@/lib/i18n';
import { searchSnippet } from '@/lib/sim/php';
import type { QueryDraft } from '@/lib/sim/query';
import { describeSort, type SortSpec } from '@/lib/sim/search/sort';
import { usePlayground } from './PlaygroundContext';
import styles from './QueryBuilder.module.css';

/**
 * The two queries, and why there are exactly two.
 *
 * Query 1 is the bounded probe: it reads the indexed slot columns and returns
 * `pageSize + 1` **ids**. Query 2 materialises exactly those ids. Neither the
 * number of conditions nor the number of matching rows changes that count —
 * which is the claim the landing page makes and this is where it is checkable.
 *
 * The SQL is generated by `lib/sim/search/compile.ts`, which is a transcription
 * of the engine's compiler, and it is *not* a caption over the row filter: the
 * evaluator and the compiler are written against the same tree and the same
 * strategy, and the headless verification asserts that the bindings the SQL
 * needs are the bindings it was given.
 */
export default function QueryPlan() {
  const { world } = usePlayground();
  const draft = world.queryDraft;
  const run = draft.lastRun;
  const t = useTranslations('playground');

  if (run?.outcome == null) return null;
  const { outcome } = run;

  return (
    <div className={`panel ${styles.panel}`}>
      <div className="panel-head">
        <span>{t('queryPlan.planLabel')}</span>
        <span className={styles.headRight}>
          <span className={`tag ${outcome.strategy === 'joins' ? 'tag-indexed' : 'tag-accent'}`}>
            <span className="dot" />
            {t('queryPlan.strategyTag', { strategy: outcome.strategy })}
          </span>
          <span className="tag tag-json">{t('queryPlan.queriesTag')}</span>
        </span>
      </div>

      <div className={styles.planBody}>
        <p className={styles.hint}>
          {outcome.strategy === 'joins' ? (
            <>
              {t('queryPlan.joinsExplanation1')}
              <code>AND</code>
              {t('queryPlan.joinsExplanation2')}
              <code>entry_slots_page_N</code>
              {t('queryPlan.joinsExplanation3')}
              <code>WHERE</code>
              {t('queryPlan.joinsExplanation4')}
            </>
          ) : (
            <>
              {t('queryPlan.existsExplanation1')}
              <code>OR</code>
              {t('queryPlan.existsExplanation2')}
              <code>NOT</code>
              {t('queryPlan.existsExplanation3')}
              <code>EXISTS</code>
              {t('queryPlan.existsExplanation4')}
            </>
          )}{' '}
          {t('queryPlan.orderedByPrefix')}
          <code>{describeSort(sortOf(draft))}</code>
          {draft.sortTarget === 'field' && <>{t('queryPlan.fieldSortSuffix')}</>}
        </p>

        <CodeBlock code={format(outcome.probe.sql)} lang="sql" title={t('queryPlan.probeTitle')} />
        <p className={styles.bindings}>
          {t('queryPlan.bindingsPrefix')}
          <code>{outcome.probe.bindings.map(renderBinding).join(', ')}</code>
        </p>

        {outcome.fetch !== null && (
          <>
            <CodeBlock
              code={format(outcome.fetch.sql)}
              lang="sql"
              title={t('queryPlan.fetchTitle')}
            />
            <p className={styles.bindings}>
              {t(outcome.probeIds.length === 1 ? 'queryPlan.probeIdsOne' : 'queryPlan.probeIdsMany', {
                count: outcome.probeIds.length,
              })}
              {t(outcome.hasMore ? 'queryPlan.hasMoreSuffix' : 'queryPlan.noMoreSuffix')}
            </p>
          </>
        )}

        <CodeBlock
          code={searchSnippet(
            world.tenantId,
            draft.modelId,
            draft.pageSize,
            draft.sortTarget,
            draft.sortFieldName,
            draft.sortDirection,
            draft.cursors.length > 0,
          )}
          lang="php"
          title={t('queryPlan.callTitle')}
          copyable
        />
      </div>
    </div>
  );
}

/**
 * The draft's sort, as the engine's optional parameter.
 *
 * The same mapping `reduce.ts` applies before calling `search()` — id
 * ascending is `null`, the ordering every read had before ADR 0041 — so the
 * caption and the query cannot disagree about which ordering ran.
 */
function sortOf(draft: QueryDraft): SortSpec | null {
  if (draft.sortTarget === 'id' && draft.sortDirection === 'asc') return null;
  return {
    target: draft.sortTarget,
    fieldName: draft.sortTarget === 'field' ? draft.sortFieldName : null,
    direction: draft.sortDirection,
  };
}

function renderBinding(value: unknown): string {
  return typeof value === 'string' ? `'${value}'` : String(value);
}

/**
 * One clause per line.
 *
 * The engine builds this as a single string because MySQL does not care, and a
 * 300-character line in a code block is unreadable. Splitting on the keywords
 * is presentation only — the SQL is not re-written, just wrapped.
 */
function format(sql: string): string {
  return sql
    .replace(/ (FROM|INNER JOIN|LEFT JOIN|CROSS JOIN|WHERE|ORDER BY|LIMIT) /g, '\n$1 ')
    .replace(/ AND (entry_data\.|EXISTS|NOT )/g, '\n  AND $1');
}
